# Generated by Django 2.1.5 on 2019-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0017_auto_20191002_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='group',
        ),
        migrations.AddField(
            model_name='spectrum',
            name='permission',
            field=models.TextField(default='private'),
        ),
    ]
