# Generated by Django 2.1.5 on 2019-11-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0018_auto_20191111_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='permission',
        ),
    ]
