# Generated by Django 2.1.5 on 2019-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0018_remove_collection_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='permission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
