version: '3'
services: 
  ### Reverseproxy server ###
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./mars_gis_django/collectstatic:/collectstatic
    depends_on:
      - django
    networks:
      redace_network:
        ipv4_address: 172.16.238.6


  ### Django ###
  django:
    build: ./mars_gis_django
    container_name: django
    # entrypoint: ["bash","./wait-for-postgis.sh"]
    volumes:
      - ./mars_gis_django:/code
      - ./mars_gis_django/mars_data:/mars_data
      # - ./todatabase_test_usui_v1:/mnt ###test
      - ../../git/mars_data_distributed:/mars_data_distributed 
    depends_on:
      - postgis
      - mapserver
      - terrainserver
    expose:
      - "8001"
    command: uwsgi --socket :8001 --module mars_gis_django.wsgi
    networks:
      redace_network:
        ipv4_address: 172.16.238.24


  ### JupyterLab ###
  # jupyterlab:
  #   ###　https: //hub.docker.com/r/jupyter/datascience-notebookからimageをpull ###
  #   image: jupyter/datascience-notebook
  #   container_name: jupyterlab
  #   ports:
  #      - 8888:8888
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   volumes:
  #     - ../work_test:/home/jovyan/work_test
  #     # - ./work1:/home/jovyan/work1
  #     # - ./work2:/home/jovyan/work2
  #     # - ./spectra:/home/jovyan/spectra
  #   command: start-notebook.sh --NotebookApp.token=''
  #   networks:
  #     redace_network:
  #       ipv4_address: 172.16.238.23


  ### JupyterHub ###
  jupyterhub:
    image: jupyterhub/jupyterhub
    build: ./jupyterhub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - "./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    networks:
      redace_network:
        ipv4_address: 172.16.238.22
  #   env_file: .env
  #   build: jupyterhub
  #   image: jupyterhub_customized
  #   hostname: jupyterhub
  #   container_name: jupyterhub
  #   volumes:
  #     - "./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   ports:
  #     - 8010:8010
  #   networks:
  #     redace_network:
  #       ipv4_address: 172.16.238.22
  #     jupyterhub_network:
  #       aliases:
  #         - jupyterhub
  #   environment:
  #     # Name of the Docker image for the single-user servers
  #     DOCKER_JUPYTER_IMAGE: ${DOCKER_JUPYTER_IMAGE}
  #     # The name of the Docker network used by the services
  #     DOCKER_NETWORK_NAME: ${COMPOSE_PROJECT_NAME}_jupyterhub_network
  #     # The IP address of the Hub service within the docker network
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager

  # # Configuration for the single-user servers
  # jupyterlab:
  #   image: ${DOCKER_JUPYTER_IMAGE}
  #   command: echo


  ### Mapserver ###
  mapserver:
    image: mapserver_nginx_20190222/redace:1.0
    container_name: mapserver
    volumes:
      - ../App/Vol_mapserver:/maps
    depends_on:
      - postgis
    expose:
      - "80"
    networks:
      redace_network:
        ipv4_address: 172.16.238.3


  ### Terrainserver ###
  terrainserver:
    image: terrainserver_nginx_20190222/redace:1.0
    container_name: terrainserver
    environment:
      - SERVE_STATIC=0
    volumes:
      - ../App/terrain/tilesets/terrain:/data/tilesets/terrain
    expose:
      - "8000"
    networks:
      redace_network:
        ipv4_address: 172.16.238.4


  ### Postgis ###
  postgis:
    image: database_postgis_20190222/redace:1.0
    container_name: postgis
    environment:
      POSTGRES_PASSWORD: anpanman
      POSTGRES_USER: m5211164
      POSTGRES_DB: mars
    volumes:
      - ./db/PostGIS_volume:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      redace_network:
        ipv4_address: 172.16.238.5



networks:
  redace_network:
    name: redace_network
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
  # jupyterhub_network:
  #   driver: overlay


# volumes:
#   jupyterhub_data:


# ### Reverseproxy server ###
#   redace_reverseproxy:
#     container_name: redace_reverseproxy
#     image: nginx:latest
#     # image: reverseproxy_nginx_20190222/redace:1.0
#     ports:
#       # - "8000:8010"
#       - "8000:80"
#     volumes:
#       - ../App/Vol_proxyserver/conf.d:/etc/nginx/conf.d
#     depends_on:
#       - web
#       # - redace_webserver
#     networks:
#       redace_network:
#         ipv4_address: 172.16.238.6

# ### Web server ###
#   redace_webserver:
#     # image: webserver_apache_20190222/redace:latest
#     image: webserver_apache_20190222/redace:1.0
#     container_name: redace_webserver
#     privileged: true
#     volumes:  
#       # - ../App/Vol_webserver/www:/var/www
#     ##########################################################################################################
#     #############  Obs data path!  Chenge here!  [ /Your_local_path1 : /mars_data ]               ############
#     ###                                                                                           ############
#     ###   "Your_local_path1" equal "obs_data_volume"                                              ############
#     ###   >>pwd                                                                                   ############
#     ###   /Your_local_path1                                                                       ############
#     ###   >>ls                                                                                    ############
#     ###   generated     distributed                                                               ############
#     ###   Then, [ - /Your_local_path1 : /mars_data ]                                              ############
#     ##########################################################################################################
  
#       # - /mnt/mars_data:/mars_data
#       # - /mnt/mars_data_distributed:/mars_data_distributed     ################## Here!!!!
#       - ../../git/mars_data:/mars_data
#       # - ../../git/mars_data_distributed:/mars_data_distributed 
#     ##########################################################################################################
#     # depends_on:
#     #   - redace_mapserver
#     #   - redace_terrainserver
#     #   - redace_postgis
#     expose:
#       - "80"
#     networks:
#       redace_network:
#         ipv4_address: 172.16.238.2