version: '3'
services: 
  ### Reverseproxy server ###
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./mars_gis_django/collect_static:/collect_static
    depends_on:
      - django
    networks:
      redace_network:
        ipv4_address: 172.16.238.6


  ### Django ###
  django:
    build: ./mars_gis_django
    container_name: django
    # entrypoint: ["bash","./wait-for-postgis.sh"]
    volumes:
      - ./mars_gis_django:/code
      - ./mars_gis_django/mars_data:/mars_data
      # - ./todatabase_test_usui_v1:/mnt ###test
      - ../../git/mars_data_distributed:/mars_data_distributed 
    depends_on:
      - postgis
      - mapserver
      - terrainserver
    expose:
      - "8001"
    command: uwsgi --socket :8001 --module mars_gis_django.wsgi
    networks:
      redace_network:
        ipv4_address: 172.16.238.24

  ### Mapserver ###
  mapserver:
    image: mapserver_nginx_20190222/redace:1.0
    container_name: mapserver
    volumes:
      - ../App/Vol_mapserver:/maps
    depends_on:
      - postgis
    expose:
      - "80"
    networks:
      redace_network:
        ipv4_address: 172.16.238.3


  ### Terrainserver ###
  terrainserver:
    image: terrainserver_nginx_20190222/redace:1.0
    container_name: terrainserver
    environment:
      - SERVE_STATIC=0
    volumes:
      - ../App/terrain/tilesets/terrain:/data/tilesets/terrain
    expose:
      - "8000"
    networks:
      redace_network:
        ipv4_address: 172.16.238.4


  ### Postgis ###
  postgis:
    image: database_postgis_20190222/redace:1.0
    container_name: postgis
    environment:
      POSTGRES_PASSWORD: anpanman
      POSTGRES_USER: m5211164
      POSTGRES_DB: mars
    volumes:
      - ./db/PostGIS_volume:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      redace_network:
        ipv4_address: 172.16.238.5



networks:
  redace_network:
    name: redace_network
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
