# Generated by Django 2.1.5 on 2019-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('mineral', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('x_pixel', models.IntegerField()),
                ('y_pixel', models.IntegerField()),
                ('wavelength', models.TextField()),
                ('reflectance', models.TextField()),
                ('mineral_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('spectra_collection_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpectraCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
    ]
