# Generated by Django 2.1.5 on 2019-01-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('x_pixel', models.IntegerField()),
                ('y_pixel', models.IntegerField()),
                ('wavelength', models.TextField()),
                ('reflectance', models.TextField()),
                ('mineral_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Spectra',
        ),
        migrations.DeleteModel(
            name='SpectraCollection',
        ),
        migrations.AddField(
            model_name='collection',
            name='spectra',
            field=models.ManyToManyField(to='spectra.Spectrum'),
        ),
    ]
