# Generated by Django 2.1.5 on 2019-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0003_remove_collection_spectra'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='spectra',
            field=models.ManyToManyField(to='spectra.Spectrum'),
        ),
    ]
