# Generated by Django 2.1.5 on 2019-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0006_collection_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='mineral_id',
            field=models.IntegerField(default=None),
        ),
    ]
