# Generated by Django 2.1.5 on 2019-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0007_auto_20190608_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='mineral_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
