# Generated by Django 2.1.5 on 2019-07-10 04:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0008_auto_20190626_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
