# Generated by Django 2.1.5 on 2019-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0009_auto_20190710_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectrum',
            old_name='point',
            new_name='geom',
        ),
    ]
