# Generated by Django 2.1.5 on 2019-07-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0010_auto_20190710_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectrum',
            old_name='geom',
            new_name='point',
        ),
    ]
