# Generated by Django 2.1.5 on 2019-07-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0011_auto_20190712_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectrum',
            old_name='point',
            new_name='geom',
        ),
    ]
