# Generated by Django 2.1.5 on 2019-07-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0012_auto_20190712_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectrum',
            old_name='geom',
            new_name='point',
        ),
    ]
