# Generated by Django 2.1.5 on 2019-07-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0013_auto_20190712_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='band_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
