# Generated by Django 2.1.5 on 2019-07-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0014_spectrum_band_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='band_number',
        ),
    ]
