# Generated by Django 2.1.5 on 2019-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0015_remove_spectrum_band_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='data_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
