# Generated by Django 2.1.5 on 2019-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0016_spectrum_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='data_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
