# Generated by Django 2.1.5 on 2019-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0018_remove_collection_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='permission',
            field=models.TextField(default='private'),
        ),
    ]
