# Generated by Django 2.1.5 on 2019-11-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0019_collection_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='permission',
        ),
    ]
