# Generated by Django 2.1.5 on 2019-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0020_remove_collection_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='permission',
            field=models.TextField(default='private'),
        ),
    ]
