# Generated by Django 2.1.5 on 2019-11-14 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0023_spectrum_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
