# Generated by Django 2.1.5 on 2020-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0024_spectrum_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='x_image_size',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectrum',
            name='y_image_size',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
