# Generated by Django 2.1.5 on 2021-12-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0025_auto_20200119_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='point',
        ),
    ]
