# Generated by Django 2.1.5 on 2021-12-11 23:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0026_remove_spectrum_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
