# Generated by Django 2.1.5 on 2022-10-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0027_spectrum_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='image_path',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
